################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Drivers/FATFS/source/diskio.c \
../Drivers/FATFS/source/ff.c \
../Drivers/FATFS/source/ffsystem.c \
../Drivers/FATFS/source/ffunicode.c 

OBJS += \
./Drivers/FATFS/source/diskio.o \
./Drivers/FATFS/source/ff.o \
./Drivers/FATFS/source/ffsystem.o \
./Drivers/FATFS/source/ffunicode.o 

C_DEPS += \
./Drivers/FATFS/source/diskio.d \
./Drivers/FATFS/source/ff.d \
./Drivers/FATFS/source/ffsystem.d \
./Drivers/FATFS/source/ffunicode.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/FATFS/source/diskio.o: ../Drivers/FATFS/source/diskio.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu99 '-DHSE_STARTUP_TIMEOUT=360000000' '-DHSE_VALUE=8000000' -DUSE_USB_OTG_FS -DUSE_ULPI_PHY -DARM_MATH_CM4 -DSTM32F469xx -D__FPU_PRESENT -c -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Core/Inc" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System/Devices" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System/Units" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/FATFS/source" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/Include" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/DSP_Lib/Include" -Ofast -ffunction-sections -fdata-sections -mslow-flash-data -fno-strict-aliasing -Wall -v -fstack-usage -MMD -MP -MF"Drivers/FATFS/source/diskio.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/FATFS/source/ff.o: ../Drivers/FATFS/source/ff.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu99 '-DHSE_STARTUP_TIMEOUT=360000000' '-DHSE_VALUE=8000000' -DUSE_USB_OTG_FS -DUSE_ULPI_PHY -DARM_MATH_CM4 -DSTM32F469xx -D__FPU_PRESENT -c -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Core/Inc" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System/Devices" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System/Units" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/FATFS/source" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/Include" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/DSP_Lib/Include" -Ofast -ffunction-sections -fdata-sections -mslow-flash-data -fno-strict-aliasing -Wall -v -fstack-usage -MMD -MP -MF"Drivers/FATFS/source/ff.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/FATFS/source/ffsystem.o: ../Drivers/FATFS/source/ffsystem.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu99 '-DHSE_STARTUP_TIMEOUT=360000000' '-DHSE_VALUE=8000000' -DUSE_USB_OTG_FS -DUSE_ULPI_PHY -DARM_MATH_CM4 -DSTM32F469xx -D__FPU_PRESENT -c -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Core/Inc" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System/Devices" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System/Units" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/FATFS/source" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/Include" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/DSP_Lib/Include" -Ofast -ffunction-sections -fdata-sections -mslow-flash-data -fno-strict-aliasing -Wall -v -fstack-usage -MMD -MP -MF"Drivers/FATFS/source/ffsystem.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/FATFS/source/ffunicode.o: ../Drivers/FATFS/source/ffunicode.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu99 '-DHSE_STARTUP_TIMEOUT=360000000' '-DHSE_VALUE=8000000' -DUSE_USB_OTG_FS -DUSE_ULPI_PHY -DARM_MATH_CM4 -DSTM32F469xx -D__FPU_PRESENT -c -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Core/Inc" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System/Devices" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System/Units" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/FATFS/source" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/Include" -I"C:/Users/Francesco/STM32CubeIDE/workspace_1.3.0/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/DSP_Lib/Include" -Ofast -ffunction-sections -fdata-sections -mslow-flash-data -fno-strict-aliasing -Wall -v -fstack-usage -MMD -MP -MF"Drivers/FATFS/source/ffunicode.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

