################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_BUS_Port.c \
../Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_I2C_Port.c \
../Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_LCD_LL.c \
../Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_RTC.c \
../Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_SPI_Port.c \
../Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_SRAM_LL.c \
../Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_Serial_Port.c \
../Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_Status_LEDs.c \
../Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_TestPads.c \
../Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_VGA_LL.c 

OBJS += \
./Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_BUS_Port.o \
./Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_I2C_Port.o \
./Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_LCD_LL.o \
./Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_RTC.o \
./Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_SPI_Port.o \
./Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_SRAM_LL.o \
./Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_Serial_Port.o \
./Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_Status_LEDs.o \
./Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_TestPads.o \
./Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_VGA_LL.o 

C_DEPS += \
./Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_BUS_Port.d \
./Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_I2C_Port.d \
./Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_LCD_LL.d \
./Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_RTC.d \
./Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_SPI_Port.d \
./Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_SRAM_LL.d \
./Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_Serial_Port.d \
./Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_Status_LEDs.d \
./Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_TestPads.d \
./Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_VGA_LL.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_BUS_Port.o: ../Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_BUS_Port.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu99 -g3 '-DHSE_STARTUP_TIMEOUT=360000000' -DSTM32F469_479xx '-DHSE_VALUE=8000000' -DUSE_USB_OTG_FS -DUSE_ULPI_PHY -DARM_MATH_CM4 -DSTM32F469xx -D__FPU_PRESENT -c -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Core/Inc" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System/Devices" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System/Units" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/FATFS/source" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/Include" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/DSP_Lib/Include" -Og -ffunction-sections -fdata-sections -mslow-flash-data -fno-strict-aliasing -Wall -v -fstack-usage -MMD -MP -MF"Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_BUS_Port.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_I2C_Port.o: ../Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_I2C_Port.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu99 -g3 '-DHSE_STARTUP_TIMEOUT=360000000' -DSTM32F469_479xx '-DHSE_VALUE=8000000' -DUSE_USB_OTG_FS -DUSE_ULPI_PHY -DARM_MATH_CM4 -DSTM32F469xx -D__FPU_PRESENT -c -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Core/Inc" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System/Devices" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System/Units" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/FATFS/source" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/Include" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/DSP_Lib/Include" -Og -ffunction-sections -fdata-sections -mslow-flash-data -fno-strict-aliasing -Wall -v -fstack-usage -MMD -MP -MF"Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_I2C_Port.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_LCD_LL.o: ../Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_LCD_LL.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu99 -g3 '-DHSE_STARTUP_TIMEOUT=360000000' -DSTM32F469_479xx '-DHSE_VALUE=8000000' -DUSE_USB_OTG_FS -DUSE_ULPI_PHY -DARM_MATH_CM4 -DSTM32F469xx -D__FPU_PRESENT -c -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Core/Inc" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System/Devices" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System/Units" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/FATFS/source" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/Include" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/DSP_Lib/Include" -Og -ffunction-sections -fdata-sections -mslow-flash-data -fno-strict-aliasing -Wall -v -fstack-usage -MMD -MP -MF"Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_LCD_LL.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_RTC.o: ../Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_RTC.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu99 -g3 '-DHSE_STARTUP_TIMEOUT=360000000' -DSTM32F469_479xx '-DHSE_VALUE=8000000' -DUSE_USB_OTG_FS -DUSE_ULPI_PHY -DARM_MATH_CM4 -DSTM32F469xx -D__FPU_PRESENT -c -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Core/Inc" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System/Devices" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System/Units" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/FATFS/source" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/Include" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/DSP_Lib/Include" -Og -ffunction-sections -fdata-sections -mslow-flash-data -fno-strict-aliasing -Wall -v -fstack-usage -MMD -MP -MF"Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_RTC.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_SPI_Port.o: ../Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_SPI_Port.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu99 -g3 '-DHSE_STARTUP_TIMEOUT=360000000' -DSTM32F469_479xx '-DHSE_VALUE=8000000' -DUSE_USB_OTG_FS -DUSE_ULPI_PHY -DARM_MATH_CM4 -DSTM32F469xx -D__FPU_PRESENT -c -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Core/Inc" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System/Devices" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System/Units" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/FATFS/source" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/Include" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/DSP_Lib/Include" -Og -ffunction-sections -fdata-sections -mslow-flash-data -fno-strict-aliasing -Wall -v -fstack-usage -MMD -MP -MF"Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_SPI_Port.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_SRAM_LL.o: ../Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_SRAM_LL.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu99 -g3 '-DHSE_STARTUP_TIMEOUT=360000000' -DSTM32F469_479xx '-DHSE_VALUE=8000000' -DUSE_USB_OTG_FS -DUSE_ULPI_PHY -DARM_MATH_CM4 -DSTM32F469xx -D__FPU_PRESENT -c -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Core/Inc" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System/Devices" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System/Units" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/FATFS/source" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/Include" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/DSP_Lib/Include" -Og -ffunction-sections -fdata-sections -mslow-flash-data -fno-strict-aliasing -Wall -v -fstack-usage -MMD -MP -MF"Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_SRAM_LL.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_Serial_Port.o: ../Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_Serial_Port.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu99 -g3 '-DHSE_STARTUP_TIMEOUT=360000000' -DSTM32F469_479xx '-DHSE_VALUE=8000000' -DUSE_USB_OTG_FS -DUSE_ULPI_PHY -DARM_MATH_CM4 -DSTM32F469xx -D__FPU_PRESENT -c -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Core/Inc" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System/Devices" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System/Units" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/FATFS/source" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/Include" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/DSP_Lib/Include" -Og -ffunction-sections -fdata-sections -mslow-flash-data -fno-strict-aliasing -Wall -v -fstack-usage -MMD -MP -MF"Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_Serial_Port.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_Status_LEDs.o: ../Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_Status_LEDs.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu99 -g3 '-DHSE_STARTUP_TIMEOUT=360000000' -DSTM32F469_479xx '-DHSE_VALUE=8000000' -DUSE_USB_OTG_FS -DUSE_ULPI_PHY -DARM_MATH_CM4 -DSTM32F469xx -D__FPU_PRESENT -c -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Core/Inc" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System/Devices" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System/Units" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/FATFS/source" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/Include" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/DSP_Lib/Include" -Og -ffunction-sections -fdata-sections -mslow-flash-data -fno-strict-aliasing -Wall -v -fstack-usage -MMD -MP -MF"Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_Status_LEDs.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_TestPads.o: ../Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_TestPads.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu99 -g3 '-DHSE_STARTUP_TIMEOUT=360000000' -DSTM32F469_479xx '-DHSE_VALUE=8000000' -DUSE_USB_OTG_FS -DUSE_ULPI_PHY -DARM_MATH_CM4 -DSTM32F469xx -D__FPU_PRESENT -c -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Core/Inc" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System/Devices" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System/Units" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/FATFS/source" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/Include" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/DSP_Lib/Include" -Og -ffunction-sections -fdata-sections -mslow-flash-data -fno-strict-aliasing -Wall -v -fstack-usage -MMD -MP -MF"Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_TestPads.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_VGA_LL.o: ../Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_VGA_LL.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu99 -g3 '-DHSE_STARTUP_TIMEOUT=360000000' -DSTM32F469_479xx '-DHSE_VALUE=8000000' -DUSE_USB_OTG_FS -DUSE_ULPI_PHY -DARM_MATH_CM4 -DSTM32F469xx -D__FPU_PRESENT -c -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Core/Inc" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System/Devices" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/ArcadeIT_Lib/System/Units" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/FATFS/source" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/Include" -I"C:/Users/info/Documents/GitHub/ArcadeIT/ArcadeIT_Ver021_F469_CMSIS/Drivers/CMSIS/DSP_Lib/Include" -Og -ffunction-sections -fdata-sections -mslow-flash-data -fno-strict-aliasing -Wall -v -fstack-usage -MMD -MP -MF"Drivers/ArcadeIT_Lib/System/Devices/ArcadeIT_VGA_LL.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

